name: 'hello-world'
description: 'github action demo'
author: 'yanai101'

inputs:
    jokeType:
        description: 'joke type (General Knock-Knock Programming)'
        default: 
            'General'

outputs:
    jokeId: 
        description: 'the joke result'

runs:
    using: 'node12'
    main: 'dist/index.js'
