
name: Dad-joke
on: [push , pull_request]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          jokeType: General
        id: joke
      - run : echo ${{steps.joke.outputs.jokeId}}    
